### ISSUE TITLE
 Error: Heartbeat timer is already running

### ISSUE THREAD

**Issue by AuHau** [ChainSafe/js-libp2p-gossipsub#132]
When I startup libp2p-gossipsub as part of libp2p I get unhandled promise rejection error as follow:

```
(node:77341) UnhandledPromiseRejectionWarning: Error: Heartbeat timer is already running
    at Heartbeat.start (/Users/adam/Projects/iovlabs/rds-ipfs/node_modules/libp2p-gossipsub/src/heartbeat.js:41:27)
    at Gossipsub.<anonymous> (/Users/adam/Projects/iovlabs/rds-ipfs/node_modules/libp2p-gossipsub/src/index.js:340:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/adam/Projects/iovlabs/rds-ipfs/node_modules/libp2p-gossipsub/src/index.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Do you have some ideas why is it happening? Can it affect something?

Currently, it seems that everything works as expected even with this error, but it raises concern...

**Comment by vasco-santos** [comment]
Hello @AuHau 
Can you let me know the versions you are using?
It seems that `gossipsub.start` is called multiple times

**Comment by AuHau** [comment]
Sure, here: https://github.com/rsksmart/rif-communications-pubsub/blob/master/package.json#L45

**Comment by vasco-santos** [comment]
So, something is triggering the second start of heartbeat. Nothing bad should be happening because it is already running.

https://github.com/ChainSafe/js-libp2p-gossipsub/blob/v0.4.6/ts/heartbeat.ts#L30
https://github.com/ChainSafe/js-libp2p-gossipsub/blob/v0.4.6/ts/index.ts#L382

We are actually removing this error from the new gossipsub code and just return if already running. However, the start should not be called twice. When you do `libp2p.start()` it calls `pubsub.start` that calls `hearbeat.start`. I could only find in your code `libp2p.start`, which seems correct. It would be nice if you could do a `console.trace()` in the source of gossipsub before the throw, so that we can see where the second start is coming from

**Comment by AuHau** [comment]
That is great idea! Should have thought of that, will try. Thanks!

**Comment by AuHau** [comment]
Hmm the trace is not much helpful as it is pretty much the same as in the first message for both of calls. I have putted before the `start()` so yes there are two call but I think they should be from different libp2p instances.

But made me think. Is it alright to spawn multiple libp2p instances? We need those for tests and maybe there is some "singleton" pattern here that leads to this duplicated call?

**Comment by vasco-santos** [comment]
> But made me think. Is it alright to spawn multiple libp2p instances?

Yes, but they should have different peerIds. It is normal to have multiple logs if you have multiple peer ids. You can also log the peer Id there, IIRC that version should have a gossipsub.peerId or gossipsub._peerId property

**Comment by AuHau** [comment]
So after bit more digging in our code, I have actually discovered that we were actually calling `start()` twice, so that was the cause 😅

But you actually helped me debugging other problems I had with your last suggestion so, thanks a lot!
