### ISSUE TITLE
Compute message-id once per message

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/js-libp2p-gossipsub#170]
Anton from Teku (thank you!) proposed an optimization to prevent computing the expensive message-id function as defined in the spec.

- Use a faster cheaper message-id function for internal message de-duplication
- If the message is new only then compute the "canonical" message-id as defined in the spec

Gossip message delivery is redundant, you would highly likely receive the same full message from several of your peers. The fast message-id function aim is to quickly check that you have already saw that message and just drop it.

**Comment by tuyennhv** [comment]
this would be a good improvement for us, right now it takes 4% of cpu if lodestar uses `subscribeAllSubnets` flag
<img width="1465" alt="Screen Shot 2021-11-30 at 17 29 25" src="https://user-images.githubusercontent.com/10568965/144030738-ddfce7fb-34b9-4af2-9e32-6fb86ebf25d5.png">

just want to leave here so that we can compare it `before` and `after` we implement the new fast message-id function

**Comment by wemeetagain** [comment]
One wrinkle to figure out, how to handle IHAVE messages we receive:

Currently:
We receive a IHAVE with msgIds. We filter potential relevant IHAVEs that we may want by those already in the seen cache.

After:
We're now using the cheap msgId to key the seen cache. (The external msgId is only used in the "message cache" of potential gossip-able messages)
We receive a IHAVE with external msgIds. We filter potential relevant IHAVEs that we may want by.... ?

If we filter by messages in the message cache, we run into the issue that messages in the message cache are likely stored for significantly less time than items in the seen cache. So IHAVEs will result in IWANTs for duplicate messages (and we'll downscore peers for duplicate messages we requested).
We could create another seen cache keyed by external msgIds, or store both internal and external msgIds in the seen cache, but this seems... wasteful?

**Comment by tuyennhv** [comment]
@wemeetagain we still keep the seen cache with the canonical message id so that IHAVE/IWANT works as before.

Right now, we may receive a message n times and we have to compute the canonical message id n times. We need to have a different cache to store by fast message id to filter duplicate messages. This is what Anton said:
```
You should compute canonical message-id once per unique gossip message. But since the Gossip message delivery is redundant, you would highly likely receive the same full message from several of your peers. The fast message-id function aim is to quickly check that you have already saw that message and just drop it. 

And again that needs to be supported and performed on the Libp2p gossip side
```

This is what I see in teku, they have a final seen cache composed from 2 different caches https://github.com/ConsenSys/teku/blob/8950318b821c61cd0e7e6c0509b6982ad1f8bd20/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/gossip/LibP2PGossipNetwork.java#L114

If we want to go simple, we can just have 2 different caches, one with canonical message id (the `seenCache`) and one with the new fast message id

**Comment by tuyennhv** [comment]
there is `fast-message-id` implementation in rust too https://github.com/libp2p/rust-libp2p/blob/245b0563ab41a37b52d1d45ddb59f8706e130a53/protocols/gossipsub/src/behaviour.rs#L1698

**Comment by dapplion** [comment]
@tuyennhv I've discovered that Node takes a huge amount of memory for ES6 Map with a very large number of keys of long strings. Please study the memory cost of this caches, it could be significant.

**Comment by tuyennhv** [comment]
> @tuyennhv I've discovered that Node takes a huge amount of memory for ES6 Map with a very large number of keys of long strings. Please study the memory cost of this caches, it could be significant.

@dapplion  fast message id is calculated using sha256 so the resulted string cache key would be always 64 in length which is not long, I'd suggest we study the memory cost in the PR

**Comment by dapplion** [comment]
> @dapplion fast message id is calculated using sha256 so the resulted string cache key would be always 64 in length which is not long, I'd suggest we study the memory cost in the PR

In my latest analysis it takes 1400 bytes in Javascript to represent a 48 bytes BLS pubkeys

**Comment by tuyennhv** [comment]
a test in lodestar shows that we compute the canonical message id up to 10 times for the same message due to the message redundancy
