### ISSUE TITLE
v03.5.0: Too many topic peers

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/js-libp2p-gossipsub#313]
**Description**
There are only 21 peers
<img width="842" alt="Screen Shot 2022-08-04 at 12 25 13" src="https://user-images.githubusercontent.com/10568965/182769351-e56498b9-540f-4d56-acad-0b84469bae68.png">

But it showed a lot of topic peers

<img width="1591" alt="Screen Shot 2022-08-04 at 12 26 08" src="https://user-images.githubusercontent.com/10568965/182769429-0f91928d-eb78-4b21-8b71-e47351ad7233.png">

Quick debug
<img width="585" alt="Screen Shot 2022-08-04 at 12 28 28" src="https://user-images.githubusercontent.com/10568965/182769691-555f193c-7b9a-4e43-b1f1-93ce73c3a447.png">

**Comment by tuyennhv** [comment]
there are too many connected peers too

<img width="1242" alt="Screen Shot 2022-08-04 at 16 58 17" src="https://user-images.githubusercontent.com/10568965/182819908-a2b14379-f907-4e54-a726-72d893f5f482.png">

looks like there are some peers disconnected without calling `GossipSub.removePeer()` properly

Expected:

<img width="1238" alt="Screen Shot 2022-08-04 at 17 00 32" src="https://user-images.githubusercontent.com/10568965/182820323-77051de0-ec68-4c99-9899-ec3f9f64d7d9.png">

**Comment by wemeetagain** [comment]
It seems that this library relies on the registrar properly registering a peer to this protocol in order for both the onPeerDisconnected and onPeerConnected routines to be triggered.
So if we get an inbound-negotiated stream with a peer and libp2p doesn't successfully get a response from the identify protocol, then the registrar won't call onPeerDisconnected for that peer. 
Likewise, if we connect to a peer, but don't get a response from the identify protocol, then we won't initiate a gossipsub stream with that peer (unless that peer opens a gossipsub stream).

I think for the purposes of networks that do not necessarily support the identify protocol (eg: ethereum network) we need the following:
- A more robust way to ensure that all closed connections with peers result in proper cleanup in the gossipsub router (rather than assume the registrar will trigger cleanup on its own)
eg:
```ts
// in gossipsub
connectionManager.addEventListener('peer:disconnect', this.onPeerDisconnected.bind(this))
```
- A way to pass a negotiated gossip stream to the router (rather than assume the registrar will open one on its own)
eg:
```ts
// in the application
const stream = await libp2p.dialProtocol(peerId, gossipsubProtocol)
gossip.addOutboundStream(peerId, stream)
```

**Comment by tuyennhv** [comment]
@wemeetagain I don't see this issue happen in the current version of lodestar, do you know how does this work earlier (pre v3.x)?

**Comment by wemeetagain** [comment]
old version of libp2p would trigger onDisconnect to all peers

https://github.com/libp2p/js-libp2p/blob/v0.36.2/src/registrar.js#L54
https://github.com/libp2p/js-libp2p/blob/v0.36.2/src/registrar.js#L122

**Comment by wemeetagain** [comment]
Current version checks the protoBook, only calls onDisconnect for protocols that are registered to the peer
https://github.com/libp2p/js-libp2p/blob/master/src/registrar.ts#L152

**Comment by tuyennhv** [comment]
this issue could be the reason why memory keeps growing since the `pushable` inside `OutboundStream` stores a lot of internal buffers inside, see https://github.com/ChainSafe/js-libp2p-gossipsub/pull/314

**Comment by tuyennhv** [comment]
resolved in latest libp2p + gossipsub
