### ISSUE TITLE
js gossipsub not working in browser.

### ISSUE THREAD

**Issue by nuel77** [ChainSafe/js-libp2p-gossipsub#381]
Hello, 
I created a basic gossipsub implementation as shown [here](https://github.com/nuel77/libp2p-mulitlang-gossip/blob/main/browser-node/src/App.js). Heavily referencing the [examples](https://github.com/libp2p/js-libp2p/tree/master/examples/pubsub) . I am always getting this error when trying to publish a message using gossipsub.
I am using libp2p with the basic create-react-app template.
```
buildRawMessage.ts:40 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Message')
    at buildRawMessage (buildRawMessage.ts:40:1)
    at GossipSub.publish (index.ts:2036:1)
    at App.js:81:1
```

**Comment by nonchip** [comment]
maybe show us `App.js:81:1` (and the remainder of it, probably)?

**Comment by nuel77** [comment]
I had attached the entire link with the issue. here it is again.
https://github.com/nuel77/libp2p-mulitlang-gossip/blob/main/browser-node/src/App.js

**Comment by nuel77** [comment]
In the repository i linked, i also created a node.js implementation using the same logic. which worked fine. Thats why it felt quite wierd when the it didnt work on browser side.

**Comment by nonchip** [comment]
literally the only difference i needed between browser and nodejs was that the browser version of `webrtc-star` gets no options, while the node one gets a `wrtc` object (just so it knows which implementation to use), otherwise there should be essentially no differences for anything you're using afaik.

**Comment by nonchip** [comment]
actually i just noticed something: you discover every bootstrap node every 100ms while a comment *claims* that "autoDial is on" (but it's not in your options object)... might wanna check if *actually* turning it on does something for you, or if it's the extremely short bootstrap interval that's messing with you (it's about a tenth of every other peer-related timer after all)

**Comment by nuel77** [comment]
ahh .. yea i was tinkering with those timings.. i did test with the larger values before I pushed the code with the smaller autodial.

**Comment by nonchip** [comment]
that's not a smaller autodial timer though. that's *no autodial config whatsoever* as far as i can tell and a smaller bootstrap-fake-discovery timer. so every few seconds autodial might (or not, depending on the defaults) happen but that's already after you "discovered" the same list of peers 10-100 times since the last time, that might confuse it a lot.

**Comment by marcus-pousette** [comment]
See this https://github.com/ChainSafe/js-libp2p-gossipsub/pull/368

**Comment by nuel77** [comment]
nice.. glad it only took 2 years ;)
