### ISSUE TITLE
Memory leak in streamsOutbound

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/js-libp2p-gossipsub#477]
**Description**
There are items inside streamsOutbound exist with the same size in 2 heap snapshots (one was taken 1 day after another)

<img width="932" alt="Screenshot 2023-12-05 at 13 33 04" src="https://github.com/ChainSafe/js-libp2p-gossipsub/assets/10568965/5ffeb136-c091-45a7-b0a3-6f1b3be4cf4e">

there are 55 OutboundStream instances

<img width="951" alt="Screenshot 2023-12-05 at 13 55 24" src="https://github.com/ChainSafe/js-libp2p-gossipsub/assets/10568965/1bad397d-ecd3-49c1-8a91-964f4f00c28a">

however there are only 50 items inside Gossipsub `peers` set

<img width="961" alt="Screenshot 2023-12-05 at 14 00 13" src="https://github.com/ChainSafe/js-libp2p-gossipsub/assets/10568965/7dcb271f-54b2-460a-8ab2-cf2c89be0568">

it means that when a peer is disconnected from node, it was removed from Gossipsub `peers` set but not `streamsOutbound` map. This is root cause of [#6129](https://github.com/ChainSafe/lodestar/issues/6129) and only happen since Lodestar v1.12

**Comment by tuyennhv** [comment]
the only way a peer was removed from `peers` set but not in `streamsOutbound` is `outboundStream?.close()` throws error. It was fixed here https://github.com/ChainSafe/js-libp2p-gossipsub/pull/471/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R855

the fix is included in release 10.1.1 of gossipsub, will try to test it in lodestar
